name: "Determine changed patterns"
description: >-
  Find patterns that have changed in pull request/ branch compared to base
  branch
author: "jonas.f.henriksen@gmail.com"
inputs:
  include_patterns:
    # This is a list of folders that should be included in the output
    # typically: "a_folder another_folder"
    required: true
    type: string

outputs:
  patterns:
    description: 'Space-separated list of matched include patterns'
    value: ${{ steps.get-changed-patterns.outputs.patterns }}

runs:
  using: "composite"
  steps:
    - name: Checkout Parent Repository
      uses: actions/checkout@v5
      with:
        fetch-depth: 0

    - name: Fetch Default Branch
      shell: bash
      run: git fetch origin ${{ github.event.repository.default_branch }}

    - name: Get Current Branch
      shell: bash
      run: |
        branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}
        echo "branch_name=$branch" >> $GITHUB_OUTPUT
      id: branch

    - name: Determine Changed Directories
      shell: bash
      id: get-changed-patterns
      run: |
        echo "Starting determination of changed patterns..."
        echo "Event name: $GITHUB_EVENT_NAME"
        echo "Repository default branch: ${{ github.event.repository.default_branch }}"
        echo "Current branch: ${{ github.event.pull_request.base.ref }}"

        if [ "$GITHUB_EVENT_NAME" = "pull_request" ]; then
          echo "Pull request event"
          MERGE_BASE=$(git merge-base origin/${{ github.event.pull_request.base.ref }} HEAD)
        elif [ -n "${{ github.event.before }}" ]; then
          echo "Push event"
          MERGE_BASE=${{ github.event.before }}
        else
          echo "Manual run or unknown event"
          MERGE_BASE=$(git merge-base origin/${{ github.event.repository.default_branch }} HEAD)
        fi

        CHANGED_FILES=$(git diff --name-only $MERGE_BASE HEAD)

        # Debugging output
        echo "base ref: ${{ github.event.pull_request.base.ref }}"
        echo "Before-commit (For pushes): ${{ github.event.before }}"
        echo "MERGE_BASE: $MERGE_BASE"
        echo "Default branch: ${{ github.event.repository.default_branch }}"
        echo "Current branch: ${{ steps.branch.outputs.branch_name }}"
        echo "Base commit: $base_commit"
        echo "Changed files: $CHANGED_FILES"

        include_patterns="${{ inputs.include_patterns }}"
        patterns=""
        # Return pattern with all parent folders
        for file in $CHANGED_FILES; do
          file=$(dirname "$file")
          while [ "$file" != "." ] && [ "$file" != "/" ]; do
            patterns="$patterns $file"
            file=$(dirname "$file")
          done
        done

        # Remove duplicates
        patterns=$(echo "$patterns" | tr ' ' '\n' | sort -u | tr '\n' ' ')

        # Filter on include_patterns, and return in the same order
        # as in include_patterns
        final_patterns=""
        for pattern in $(echo "$include_patterns" | tr " |" "\n"); do
          if echo "$patterns" | grep -qw "$pattern"; then
            final_patterns="$final_patterns $pattern"
          fi
        done

        echo ""
        echo "###############################################################"
        echo "# Changed folders to be returned: $final_patterns"
        echo "###############################################################"
        echo "patterns=$final_patterns" >> $GITHUB_OUTPUT
