name: Deploy to server

on:
  workflow_dispatch:

env:
  SERVER: ${{ vars.SERVER }}
  WEB_ROOT: ${{ vars.WEB_ROOT }}
  HOST_PUBKEY: ${{ vars.HOST_PUBKEY }}
  SSH_KEY: ${{ secrets.SSH_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST_PUBKEY" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          ssh $SERVER \
            "cd webroots/$WEB_ROOT && git reset --hard origin/main"
