name: Deploy to server

on:
  workflow_dispatch:

env:
  SERVER: ${{ vars.SERVER }}
  WEB_ROOT: ${{ vars.WEB_ROOT }}
  HOST_PUBKEY: ${{ vars.HOST_PUBKEY }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  USERNAME: ${{ vars.USERNAME }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout workflow repo
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "$HOST_PUBKEY" >> ~/.ssh/known_hosts

      - name: Deploy via SSH
        run: |
          COMMANDS=$(cat <<'ENDSSH'
            cd webroots/$WEB_ROOT
            git fetch
            git reset --hard origin/main
            composer install --no-dev --optimize-autoloader
            # php bin/phinx migrate -e development
            # Legg til flere kommandoer her om ønskelig
          ENDSSH
          )
          echo "$COMMANDS"
          ssh $USERNAME@$SERVER -i ~/.ssh/id_rsa "$COMMANDS"
